on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  
jobs:
  style:
    name: stylua code style checking
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: JohnnyMorganz/stylua-action@v2
      with:
        token: ${{ secrets.STYLUA_GITHUB_TOKEN }}
        version: latest
        args: --check addons
