on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  style:
    name: StyLua
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.GH_TOKEN }}
        submodules: true
    - uses: JohnnyMorganz/stylua-action@v2
      with:
        token: ${{ secrets.GH_TOKEN }}
        version: latest
        args: --check addons
