name: Update Luvit Submodule
on: [workflow_dispatch, repository_dispatch]

jobs:
  submodule-update:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3
        name: Checkout the current fork
        with:
          path: 'fork'
          fetch-depth: 0
          token: ${{ secrets.PAT }}
      
      - name: Checkout and setup the main branch
        working-directory: $GITHUB_WORKSPACE/fork
        run: |
          git checkout main
          git remote add upstream https://github.com/LuaLS/LLS-Addons.git
          git fetch upstream
          git reset --hard upstream/main

      - name: Delete update-luvit branch (if exists)
        continue-on-error: true
        working-directory: $GITHUB_WORKSPACE/fork
        run: |
          git push origin -d update-luvit
          git push --all origin

      - name: Create a new branch and check it out
        working-directory: $GITHUB_WORKSPACE/fork
        run: |
          git checkout -b update-luvit

      - name: Update the Luvit submodule
        working-directory: $GITHUB_WORKSPACE/fork
        run: |
          git submodule update --init --checkout --force -- addons/luvit/module
          cd addons/luvit/module
          git pull origin release

      - name: Push the update branch
        working-directory: $GITHUB_WORKSPACE/fork
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m 'chore: update Luvit module'
          git push --all origin

      - name: Open a Pull Request
        env:
          GH_TOKEN: ${{ secrets.PAT }}
        run: "gh pr create --repo LuaLS/LLS-Addons --base main --head Bilal2453:update-luvit --title 'update: Luvit module' --body 'Update the Luvit module to latest [release](https://github.com/Bilal2453/luvit-meta/blob/release) branch. This PR is triggered by a [luvit-meta](https://github.com/Bilal2453/luvit-meta) [release](https://github.com/Bilal2453/luvit-meta/blob/release).'"
